### ISSUE TITLE
decide what framework to port to

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/mongs#29]
Aspen is shedding its request and response objects, to become a "parasitic web framework" (https://github.com/gratipay/aspen.py/issues/526). What do we want to do over here on Mongs? The plan over on the Aspen project is to officially support `Flask-Aspen` and `django-aspen` adapters. Perhaps `Flask-Aspen` would make sense for Mongs?

@jaraco Given your familiarity with CherryPy, another option would be for you to write and maintain a `CherryPy-Aspen` adapter, and port Mongs to that.

A third option would be to port to Flask, Django, or CherryPy _without_ the Aspen plugin.

**Comment by jaraco** [comment]
My preference would be for Flask-Aspen (or CherryPy-Aspen, but I don't want to write it).

**Comment by whit537** [comment]
Okay. We've got a Flask shim inline in Aspen on https://github.com/gratipay/aspen.py/pull/527. Once that PR lands we can start porting here. Eventually the plan is to factor out `Flask-Aspen` into its own library.

**Comment by jaraco** [comment]
The latest version runs on Pando, so that's good enough for me.
